USE BDEX3_REDESOCIAL;

select NOME_USUARIO, SOBRENOME, EMAIL 
FROM USUARIOS;

select NOME_GRUPO, DESCRICAO 
FROM  GRUPOS;

select P.ID_POST, P.TEXTO, P.IMAGEM, P.DATA_HORA, CONCAT_WS('',U.NOME_USUARIO,U.SOBRENOME) NOME_USUARIO 
FROM POSTAGENS as P join USUARIOS as U
ON U.ID_USUARIO = P.USUARIO;